services:
  deeply-shallow-eval:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deeply-shallow-eval
    volumes:
      - ./api/storage:/api/storage
    ports:
      - "8505:8505"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - deeply-shallow-net

networks:
  deeply-shallow-net:
    driver: bridge
